language: cpp
compiler: g++

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

script:
    - make
    - ./cp-tools -v
    - ./cp-tools init

after_sucess:
    - echo "Success"

after_failure:
    - echo "Failure"
