language: cpp
compiler: g++

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

script:
    - make
    - ./cp-tools

after_sucess:
    - echo "Success"

after_failure:
    - echo "Failure"
